---
title: "PCA_permanovas_individ_hours"
author: "allyson_demerlis"
date: "2023-03-22"
output: html_document
---
# Install and load necessary packages
```{r, install/load packages}
#if you need to install all the packages, you need the package "BiocManager" first.
# if (!require("BiocManager",quietly=TRUE))
#   install.packages("BiocManager")
#Now you can use BiocManager to install pacakges like DESeq2
#BiocManager::install("DESeq2")

library(DESeq2)

library(DEGreport) # needs BiocManager
  #DEGreport requires lasso2, which is not available for newer versions of R. To install lasso2, run library(remotes) (might need to install that package first), then run:
#install_version("lasso2", "1.2-22")

library(tidyverse) 

library(Rgraphviz) # needs BiocManager
library(factoextra) #for PCA and eigenvectors
library(vegan) #for adonis function for PCA

library(ggpubr)
```

# Read in RDS files
```{r}
dds_0 <- readRDS("rds_files/dds_0.rds")
dds_1 <- readRDS("rds_files/dds_1.rds")
dds_2 <- readRDS("rds_files/dds_2.rds")
dds_4 <- readRDS("rds_files/dds_4.rds")
```

# Principal component analyses and Scree plots
```{r}
#need to transform the data for plotting
dds_vst0<- vst(dds_0,blind=FALSE)
plotPCA(dds_vst0)
#plotPCA is one function to do it, or you can use the "prcomp" function, which lets you create a scree plot
pca_h0 <- prcomp(t(assay(dds_vst0)))
fviz_eig(pca_h0)

dds_vst1<- vst(dds_1,blind=FALSE)
plotPCA(dds_vst1)
pca_h1 <- prcomp(t(assay(dds_vst1)))
fviz_eig(pca_h1)

dds_vst2<- vst(dds_2,blind=FALSE)
plotPCA(dds_vst2)
pca_h2 <- prcomp(t(assay(dds_vst2)))
fviz_eig(pca_h2)

dds_vst4<- vst(dds_4,blind=FALSE)
plotPCA(dds_vst4)
pca_h4 <- prcomp(t(assay(dds_vst4)))
fviz_eig(pca_h4)
```


## PCA figures for manuscript
```{r}
#plotting the PCA in ggplot
pca12_0 <- plotPCA(dds_vst0,intgroup=c("condition"),returnData = TRUE)
pca_0 = ggplot(pca12_0, aes(PC1,PC2,shape=condition,color=condition)) + 
  geom_point(size=3) +  
  xlab(paste0("PC1 (49%)")) +
  ylab(paste0("PC2 (24%)")) +
  theme(legend.position="right")  + 
  theme_classic() +
  geom_polygon(mapping = aes(fill = condition), alpha = 0.5) +
  scale_color_manual(values = c("lightskyblue2", "salmon1")) +
  scale_fill_manual(values = c("lightskyblue2", "salmon1"))

pca12_1 <- plotPCA(dds_vst1,intgroup=c("condition"),returnData = TRUE)
pca_1 = ggplot(pca12_1, aes(PC1, PC2,shape=condition,color=condition)) + 
  geom_point(size=3) + 
  xlab(paste0("PC1 (38%)")) +
  ylab(paste0("PC2 (23%)")) +
  theme(legend.position="right") +
  theme_classic() +
  geom_polygon(mapping = aes(fill = condition), alpha = 0.5) +
  scale_color_manual(values = c("lightskyblue2", "salmon1")) +
  scale_fill_manual(values = c("lightskyblue2", "salmon1"))

pca12_2 <- plotPCA(dds_vst2,intgroup=c("condition"),returnData = TRUE)
pca_2 = ggplot(pca12_2, aes(PC1, PC2,shape=condition,color=condition)) + 
  geom_point(size=3) +   
  xlab(paste0("PC1 (35%)")) +
  ylab(paste0("PC2 (29%)")) +
  theme(legend.position="right") +
  theme_classic() +
  geom_polygon(mapping = aes(fill = condition), alpha = 0.5)+
  scale_color_manual(values = c("lightskyblue2", "salmon1")) +
  scale_fill_manual(values = c("lightskyblue2", "salmon1"))

pca12_4 <- plotPCA(dds_vst4,intgroup=c("condition"),returnData = TRUE)
pca_4 = ggplot(pca12_4, aes(PC1, PC2,shape=condition,color=condition)) + 
  geom_point(size=3) +  
  xlab(paste0("PC1 (56%)")) +
  ylab(paste0("PC2 (21%)")) +
  theme(legend.position="right") +
  theme_classic() +
  geom_polygon(mapping = aes(fill = condition), alpha = 0.5)+
  scale_color_manual(values = c("lightskyblue2", "salmon1")) +
  scale_fill_manual(values = c("lightskyblue2", "salmon1"))

pca_combined<-ggarrange(pca_0,pca_1,pca_2,pca_4,
          common.legend = TRUE,
          legend="right",
          labels=c("A","B","C","D"),
          ncol=2,nrow=2)

pca_combined

#ggsave("../4_Figures/PCA_4hours_combined.png",pca_combined,width=8,height=6)
```


# PERMANOVAs
## for hour 0
```{r}
#got this code from Kevin Wong's Physiology Analysis html

#we use the dds object instead of the original countdata_0 matrix because this has filtered out genes with low counts (<10)
hour0_countsmatrix <- assay(dds_0)
t(hour0_countsmatrix) -> hour0_countsmatrix 

#import metadata file
metadata <- readRDS("rds_files/metadata.rds")

metadata_0 <- metadata %>% filter(hour == "0")

PCA.h0.countsdata <- merge(metadata_0, hour0_countsmatrix, by='row.names', all=TRUE)

# scale data
vegan_h0 <- scale(PCA.h0.countsdata[c(5:19451)]) #we just want to scale the gene counts

# PERMANOVA 
permanova_h0 <-adonis2(vegan_h0 ~ condition, data = PCA.h0.countsdata, method='eu', na.rm=TRUE, nperm = 999)
permanova_h0 #not significant
```

## PERMANOVA for hour 1
```{r}
#we use the dds object instead of the original countdata_0 matrix because this has filtered out genes with low counts (<10)
hour1_countsmatrix <- assay(dds_1)
t(hour1_countsmatrix) -> hour1_countsmatrix 

metadata_1 <- metadata %>% filter(hour == "1")

PCA.h1.countsdata <- merge(metadata_1, hour1_countsmatrix, by='row.names', all=TRUE)

# scale data
vegan_h1 <- scale(PCA.h1.countsdata[c(5:19536)]) #we just want to scale the gene counts

# PERMANOVA 
permanova_h1 <-adonis2(vegan_h1 ~ condition, data = PCA.h1.countsdata, method='eu', na.rm=TRUE, nperm = 999)
permanova_h1 #not significant
```

## PERMANOVA for hour 2
```{r}
#we use the dds object instead of the original countdata_0 matrix because this has filtered out genes with low counts (<10)
hour2_countsmatrix <- assay(dds_2)
t(hour2_countsmatrix) -> hour2_countsmatrix 

metadata_2 <- metadata %>% filter(hour == "2")

PCA.h2.countsdata <- merge(metadata_2, hour2_countsmatrix, by='row.names', all=TRUE)

# scale data
vegan_h2 <- scale(PCA.h2.countsdata[c(5:19779)]) #we just want to scale the gene counts

# PERMANOVA 
permanova_h2<-adonis2(vegan_h2 ~ condition, data = PCA.h2.countsdata, method='eu', na.rm=TRUE, nperm = 999)
permanova_h2 #not significant
```

## PERMANOVA for hour 4
```{r}
#we use the dds object instead of the original countdata_0 matrix because this has filtered out genes with low counts (<10)
hour4_countsmatrix <- assay(dds_4)
t(hour4_countsmatrix) -> hour4_countsmatrix 

metadata_4 <- metadata %>% filter(hour == "4")

PCA.h4.countsdata <- merge(metadata_4, hour4_countsmatrix, by='row.names', all=TRUE)

# scale data
vegan_h4 <- scale(PCA.h4.countsdata[c(5:19773)]) #we just want to scale the gene counts

# PERMANOVA 
permanova_h4 <-adonis2(vegan_h4 ~ condition, data = PCA.h4.countsdata, method='eu', na.rm=TRUE, nperm = 999)
permanova_h4 #not significant
```

